### ISSUE TITLE
set a list in a redis cluster returns a error

### ISSUE THREAD

**Issue by raphapr** [jkaye2012/Redis.jl#23] opened 2016-02-05 03:13 UTC
Hello,
I found this error after trying set a list through rpush in a redis cluster:

```
conn = RedisConnection(host="localhost")
pipe = open_pipeline(conn)
rpush(conn,"foo","bar")
```

returns

```
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{Redis.ServerException}, ::ASCIIString)
This may have arisen from a call to the constructor Redis.ServerException(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Redis.ServerException(::AbstractString, !Matched::AbstractString)
  Redis.ServerException(::Any, !Matched::Any)
  call{T}(::Type{T}, ::Any)
  ...
 in parseline at /home/raphael/.julia/v0.4/Redis/src/parser.jl:50
 in rpush at /home/raphael/.julia/v0.4/Redis/src/client.jl:83
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/raphael/teste.jl, in expression starting on line 7
```

Same error with other data types.

I'd like to know if it has support to redis cluster.

Thanks

**Comment by jkaye2012** [comment] 2016-02-08 21:10
Hi there,

I haven't played with Redis cluster very much yet. I was under the impression that a standard client should support the basic commands, but apparently I was mistaken. I'll take a look at it this weekend.

Cheers,
Jordan

**Comment by jkaye2012** [comment] 2016-02-08 21:15
One quick clarification - does this command work for you without using a pipeline (or a transaction - just the raw command)?

Thanks,
Jordan

**Comment by jkaye2012** [comment] 2016-03-04 19:21
Any response to my previous question? It's pretty important because pipeline doesn't appear to be fully supported by Redis Cluster at this time, unless I'm mistaken.

**Comment by merl-dev** [comment] 2016-03-09 11:56
just chiming in here, I am also starting to work with Redis Cluster, and have been using your library in production for ever so long in non-cluster mode...great work!

Your client works exactly as expected when working with a cluster ... in the absence of a ClusterConnection/Manager type, each node must have its own connection, so you need to figure out where (which node) to set or get a key.  Pick the wrong node/connection and you get the infamous MOVED error 
MethodError(convert,(Redis.ServerException,"MOVED 15848 127.0.0.1:20003"))

for example I have 4 RedisConnections
`rs` - to a single non-clustered instance
`rn1`...`rn3` - 3 nodes of a cluster

and I execute the following

julia> `map(x->try lpush(x,"{a}:test:q1",1,2,3) catch err println(err); end,[rs,rn1,rn2,rn3])`

MethodError(convert,(Redis.ServerException,"MOVED 15495 127.0.0.1:20003"))
MethodError(convert,(Redis.ServerException,"MOVED 15495 127.0.0.1:20003"))
4-element Array{Any,1}:
 3
  nothing
  nothing
 3

1. the first 2 method errors come from pushing to node 1 and 2 where it was rejected, and we are told this should go to node 3 (at port 20003).
2. the 4 element array indicates that the single instance took the "implied" multi, as did the third node.

**From the redis docs [redis.io cluster tutorial ](http://redis.io/topics/cluster-tutorial)**:
    *Redis Cluster supports multiple key operations as long as all the keys involved into a single command execution (or whole transaction, or Lua script execution) all belong to the same hash slot. __The user can force multiple keys to be part of the same hash slot by using a concept called hash tags__.
    Hash tags are documented in the Redis Cluster specification, but the gist is that if there is a substring between {} brackets in a key, only what is inside the string is hashed, so for example this{foo}key and another{foo}key are guaranteed to be in the same hash slot, and can be used together in a command with multiple keys as arguments.*

So the workaround I have been using is to implement my own sharding.

Hope this helps.

**Comment by jkaye2012** [comment] 2016-06-21 20:47
Closing this for now as it seems like everything is working as intended.

**Closed by jkaye2012** 2016-06-21 20:47 UTC
